config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :reservations, only: %i[index destroy] do
    collection do
      post :bulk_create
      get :import
    end
  end

  root to: 'reservations#import'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  require 'csv'
  require 'date'

  def self.import(file)
    CSV.foreach(file, col_sep: ';', headers: :first_row) do |row|
        Reservation.create(
          billet_number: row["Numero billet"]&.to_i,
          reservation_number: row["Reservation"]&.to_i,
          reservation_date: row["Date reservation"],
          reservation_hour: row["Heure reservation"],
          spectacle_key: row["Cle spectacle"]&.to_i,
          spectacle: row["Spectacle"],
          representation_key: row["Cle representation"]&.to_i,
          representation: row["Representation"],
          representation_date: row["Date reservation"],
          representation_hour: row["Heure representation"],
          representation_end_date: row["Date fin representation"],
          representation_end_hour: row["Heure fin representation"],
          price: row["Prix"]&.to_i,
          product_type: row["Type de produit"],
          sale_company: row["Filiere de vente"],
          last_name: row["Nom"],
          first_name: row["Prenom"],
          email: row["Email"],
          adress: row["Adresse"],
          zipcode: row["Code postal"],
          country: row["Pays"],
          age: row["Age"]&.to_i,
          gender: row["Sexe"],
        )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
  end

  def bulk_create
    if params[:file]

      Reservation.import(params[:file])
      redirect_to action: 'index'
    else

      render :import, status: :unprocessable_entity
    end
  end

  def import; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CSV IMPORT AND TABLE SYSTEM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/import.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CSV IMPORT AND TABLE SYSTEM</title>
</head>
<body class= "body">

  <div class="container">
    <div class="import">
      <h1>Import CSV file</h1>
      <div class="import-file">
        <%= form_tag bulk_create_reservations_path, multipart: true do %>
          <span class= "btn-add"> <%= file_field_tag :file %> </span>
          <%= submit_tag "Importer CSV", class: "btn-submit"  %>
        <% end %>
      </div>
    </div>


<div>
    <% if Reservation.any? %>
      <%= link_to "Accéder au tableau", reservations_path%>
    <% else @reservations.nil? %>
     <p> Aucun tableau disponible</p>
    <% end %>

  </div>

  </div>



</body>
</html>

app/views/reservations/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CSV IMPORT AND TABLE SYSTEM</title>
</head>
<body class="index-body">

<%= link_to "Importer un CSV", import_reservations_path,  class: "btn-submit" %>

<h1> Tableau récapitulatif</h1>

  <div class="table">
    <table>
      <thead>
        <tr>
          <th>Numero billet</th>
          <th>Réservation</th>
          <th>Date et heure de réservation</th>
          <th>Clé spectacle</th>
          <th>Spectacle</th>
          <th>Clé représentation</th>
          <th>Représentation</th>
          <th>Date et heure de la représentation</th>
          <th>Date et heure de fin de la représentation</th>
          <th>Prix</th>
          <th>Type de produit</th>
          <th>Filiere de vente</th>
          <th>Nom</th>
          <th>Prenom</th>
          <th>Email</th>
          <th>Adresse</th>
          <th>Code Postal</th>
          <th>Pays</th>
          <th>Age</th>
          <th>Sexe</th>
        </tr>
      </thead>

      <tbody>
        <% @reservations.each do |reservation| %>
          <tr>
            <td><%= reservation.billet_number %></td>
            <td><%= reservation.reservation_number %></td>
            <td><%= reservation.reservation_date.strftime("%y/%m/%d").to_s %>
                <%= reservation.reservation_hour.time.strftime("%Hh%M") %></td>
            <td><%= reservation.spectacle_key %></td>
            <td><%= reservation.spectacle %></td>
            <td><%= reservation.representation_key %></td>
            <td><%= reservation.representation %></td>
            <td><%= reservation.representation_date.strftime("%y/%m/%d").to_s %>
                <%= reservation.representation_hour.time.strftime("%Hh%M") %></td>
            <td><%= reservation.representation_end_date.strftime("%y/%m/%d").to_s %>
                <%= reservation.representation_end_hour.time.strftime("%Hh%M") %></td>
            <td><%= reservation.price %></td>
            <td><%= reservation.product_type %></td>
            <td><%= reservation.sale_company %></td>
            <td><%= reservation.last_name %></td>
            <td><%= reservation.first_name %></td>
            <td><%= reservation.email %></td>
            <td><%= reservation.adress %></td>
            <td><%= reservation.zipcode %></td>
            <td><%= reservation.country %></td>
            <td><%= reservation.age %></td>
            <td><%= reservation.gender %></td>
          </tr>
        <% end  %>
      </tbody>
    </table>
  </div>

  <h1>Useful Datas</h1>

  <div class="syntetic-table">
    <table >
        <thead class ="syntetic-head">
          <tr>
            <th>Nombre total de réservations</th>
            <th>Nombre d'acheteurs uniques</th>
            <th>Moyenne d'âge</th>
            <th>Prix moyen par représentation</th>
          </tr>
        </thead>
        <tbody class="syntetic-body">
          <tr>
            <td> <%=@reservations.count  %> </td>
            <td> <%=@reservations.pluck(:email).uniq.reject(&:nil?).count  %></td>
            <td> <%= reservations = @reservations.uniq(&:email).reject{ |reservation|   reservation.age.nil? }
                    mean = reservations.sum(&:age) / reservations.count %></td>

            <td>
                  <%  price_per_representation = @reservations.group(:representation_key).average(:price) %>
                  <%  price_per_representation.each do |key, value| %>
                 <ul>
                 <li> Clé représentation <%= key %> :  <%= value.to_f.round(2) %></li>
                 </ul>

                  <% end %>
            </td>
          </tr>

        </tbody>
      </table>
  </div>







</body>
</html>